spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: Danilo0102*
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: create-drop
    generate-ddl: true